services:
  nodejs-app:
    container_name: yaqij.homepage.container
    image: yaqij.homepage
    build:
      context: ./homepage
      target: production
    environment:
      - NODE_ENV=production
    ports:
      - 4192:3000
  
  nodejs-dev:
    container_name: yaqij.homepage-dev.container
    image: yaqij.homepage
    build:
      context: ./homepage
      target: dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./homepage/app:/app/app
    ports:
      - 4192:3000

  spring:
    container_name: yaqij.brain.container
    image: yaqij.brain
    build:
      context: ./brain
    ports:
      - 4191:8080
